//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdministradorMedicoExcepciones {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdministradorMedicoExcepciones() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Libreria.Resource.AdministradorMedicoExcepciones", typeof(AdministradorMedicoExcepciones).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La consulta se encuentra cerrada.
        /// </summary>
        public static string ConsultaCerrada {
            get {
                return ResourceManager.GetString("ConsultaCerrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha enviado la fecha, o es incorrecta.
        /// </summary>
        public static string ErrorFechaNull {
            get {
                return ResourceManager.GetString("ErrorFechaNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El horario seleccionado no se pudo obtener o ya fue tomado.
        /// </summary>
        public static string ErrorHorarioDisponibleNoEcontrado {
            get {
                return ResourceManager.GetString("ErrorHorarioDisponibleNoEcontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede acceder a turnos de otro profesional.
        /// </summary>
        public static string ErrorProfesionalNoTurno {
            get {
                return ResourceManager.GetString("ErrorProfesionalNoTurno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El profesional no corresponde al ambito.
        /// </summary>
        public static string ErrorProfesionalNull {
            get {
                return ResourceManager.GetString("ErrorProfesionalNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El profesional no tiene especialidad asignada.
        /// </summary>
        public static string ErrorProfesionalSinEspcialidad {
            get {
                return ResourceManager.GetString("ErrorProfesionalSinEspcialidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se permite la modificacion del codigo, lo cual conlleva a una violacion del contrato, se registro un evento de modificacion de codigo en el modulo de: {0} en fecha: {1} , efectuada por el usuario {2}, ha sido registrado e informado, Descripcion: {3}.
        /// </summary>
        public static string ExcepcionModificacionCodigo {
            get {
                return ResourceManager.GetString("ExcepcionModificacionCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentran horarios disponibles para el profesional en la fecha seleccionada.
        /// </summary>
        public static string ExcepcionSinHorariosDisponibles {
            get {
                return ResourceManager.GetString("ExcepcionSinHorariosDisponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede agendar turnos dado que no posee profesionales medicos asignados para administrar.
        /// </summary>
        public static string ExcepcionSinProfecionalesAsignados {
            get {
                return ResourceManager.GetString("ExcepcionSinProfecionalesAsignados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La especialidad no tiene consultorios asignados.
        /// </summary>
        public static string ExceptionEspecialidadSinConsultorio {
            get {
                return ResourceManager.GetString("ExceptionEspecialidadSinConsultorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede realiazar la modificacion debido a que su pefil no cuenta con los permisos correspondientes.
        /// </summary>
        public static string ExceptionNoEditaInformacion {
            get {
                return ResourceManager.GetString("ExceptionNoEditaInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede realizar la modificacion debido a que el profesional no esta dentro de su perfil de administracion.
        /// </summary>
        public static string ExepctionProfecionalNoasignado {
            get {
                return ResourceManager.GetString("ExepctionProfecionalNoasignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede agregar horarioa disponibles a fechas anteriores al dia de hoy: {0}, la fecha selecionada fue: {1}.
        /// </summary>
        public static string FechaMenorAFechaActual {
            get {
                return ResourceManager.GetString("FechaMenorAFechaActual", resourceCulture);
            }
        }
    }
}
