//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdministradorMedicoMensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdministradorMedicoMensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Libreria.Resource.AdministradorMedicoMensajes", typeof(AdministradorMedicoMensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha asignado su perfil profecional a una nueva empresa.
        /// </summary>
        public static string AlertaAsignacion {
            get {
                return ResourceManager.GetString("AlertaAsignacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha recibido una votacion Negativa.
        /// </summary>
        public static string AlertaVotacionNegativa {
            get {
                return ResourceManager.GetString("AlertaVotacionNegativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha recibido una votacion positiva.
        /// </summary>
        public static string AlertaVotacionPositiva {
            get {
                return ResourceManager.GetString("AlertaVotacionPositiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La informacion ha sido guardada exitosamente.
        /// </summary>
        public static string InformacionPersonalGuardada {
            get {
                return ResourceManager.GetString("InformacionPersonalGuardada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El turno ha sido agendado exitosamente para la fecha: {0} en la especialidad {1} con el medico {2} en el consultorio {3}.
        /// </summary>
        public static string TurnoAgendado {
            get {
                return ResourceManager.GetString("TurnoAgendado", resourceCulture);
            }
        }
    }
}
