//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdministradorMedicoUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdministradorMedicoUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Libreria.Resource.AdministradorMedicoUI", typeof(AdministradorMedicoUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string Agenda {
            get {
                return ResourceManager.GetString("Agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string MenuAgenda {
            get {
                return ResourceManager.GetString("MenuAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MenuError {
            get {
                return ResourceManager.GetString("MenuError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesional.
        /// </summary>
        public static string MenuPerfilProfesional {
            get {
                return ResourceManager.GetString("MenuPerfilProfesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesionales.
        /// </summary>
        public static string MenuProfesionales {
            get {
                return ResourceManager.GetString("MenuProfesionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrar Agenda.
        /// </summary>
        public static string ModuloAgenda {
            get {
                return ResourceManager.GetString("ModuloAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactanos.
        /// </summary>
        public static string ModuloError {
            get {
                return ResourceManager.GetString("ModuloError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerfilProfesional.
        /// </summary>
        public static string ModuloPerfilProfesional {
            get {
                return ResourceManager.GetString("ModuloPerfilProfesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesionales.
        /// </summary>
        public static string ModuloProfesionales {
            get {
                return ResourceManager.GetString("ModuloProfesionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservar Turno.
        /// </summary>
        public static string ModuloReservaTurno {
            get {
                return ResourceManager.GetString("ModuloReservaTurno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione Especialidad:.
        /// </summary>
        public static string SeleccioneEspecialidad {
            get {
                return ResourceManager.GetString("SeleccioneEspecialidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione Profesional:.
        /// </summary>
        public static string SeleccioneProfesional {
            get {
                return ResourceManager.GetString("SeleccioneProfesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrar Agenda Profesional.
        /// </summary>
        public static string TituloAgenda {
            get {
                return ResourceManager.GetString("TituloAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un Error.
        /// </summary>
        public static string TituloError {
            get {
                return ResourceManager.GetString("TituloError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil Profesional.
        /// </summary>
        public static string TituloPerfilProfecional {
            get {
                return ResourceManager.GetString("TituloPerfilProfecional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administracion de Profesionales.
        /// </summary>
        public static string TituloProfesionales {
            get {
                return ResourceManager.GetString("TituloProfesionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservar Turno.
        /// </summary>
        public static string TituloReservarTurno {
            get {
                return ResourceManager.GetString("TituloReservarTurno", resourceCulture);
            }
        }
    }
}
