//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Libreria.Resource.MenuResource", typeof(MenuResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abonos.
        /// </summary>
        public static string Abono {
            get {
                return ResourceManager.GetString("Abono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        public static string Acciones {
            get {
                return ResourceManager.GetString("Acciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almacenes.
        /// </summary>
        public static string Almacen {
            get {
                return ResourceManager.GetString("Almacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artistas.
        /// </summary>
        public static string Artista {
            get {
                return ResourceManager.GetString("Artista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baja.
        /// </summary>
        public static string Baja {
            get {
                return ResourceManager.GetString("Baja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comptas.
        /// </summary>
        public static string Compras {
            get {
                return ResourceManager.GetString("Compras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuracion de Accesos.
        /// </summary>
        public static string ConfiguracionAcceso {
            get {
                return ResourceManager.GetString("ConfiguracionAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuraciones del Sistema.
        /// </summary>
        public static string ConfiguracionSistema {
            get {
                return ResourceManager.GetString("ConfiguracionSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contabilidad.
        /// </summary>
        public static string Contabilidad {
            get {
                return ResourceManager.GetString("Contabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciales.
        /// </summary>
        public static string Credencial {
            get {
                return ResourceManager.GetString("Credencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuentas Bancarias.
        /// </summary>
        public static string Cuentas {
            get {
                return ResourceManager.GetString("Cuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuentos.
        /// </summary>
        public static string Descuentos {
            get {
                return ResourceManager.GetString("Descuentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egresos de Caja.
        /// </summary>
        public static string EgresosCaja {
            get {
                return ResourceManager.GetString("EgresosCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entradas.
        /// </summary>
        public static string Entradas {
            get {
                return ResourceManager.GetString("Entradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estand.
        /// </summary>
        public static string Estand {
            get {
                return ResourceManager.GetString("Estand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiquetas.
        /// </summary>
        public static string Etiqueta {
            get {
                return ResourceManager.GetString("Etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento.
        /// </summary>
        public static string Evento {
            get {
                return ResourceManager.GetString("Evento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas Pendientes.
        /// </summary>
        public static string FacturasPendientes {
            get {
                return ResourceManager.GetString("FacturasPendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feria Exposicion.
        /// </summary>
        public static string Feria {
            get {
                return ResourceManager.GetString("Feria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresos.
        /// </summary>
        public static string Ingreso {
            get {
                return ResourceManager.GetString("Ingreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresos de Caja.
        /// </summary>
        public static string IngresosCaja {
            get {
                return ResourceManager.GetString("IngresosCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresos de Stock.
        /// </summary>
        public static string IngresoStock {
            get {
                return ResourceManager.GetString("IngresoStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista GiftCards.
        /// </summary>
        public static string ListaGiftCards {
            get {
                return ResourceManager.GetString("ListaGiftCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Ventas.
        /// </summary>
        public static string ListaVentas {
            get {
                return ResourceManager.GetString("ListaVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensajes de Pagina.
        /// </summary>
        public static string MensajeContacto {
            get {
                return ResourceManager.GetString("MensajeContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulos.
        /// </summary>
        public static string Modulos {
            get {
                return ResourceManager.GetString("Modulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda.
        /// </summary>
        public static string Moneda {
            get {
                return ResourceManager.GetString("Moneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes de Finaciacion.
        /// </summary>
        public static string PlanesFinancieros {
            get {
                return ResourceManager.GetString("PlanesFinancieros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuentas Por Cobrar.
        /// </summary>
        public static string PorCobrar {
            get {
                return ResourceManager.GetString("PorCobrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuentas por Pagar.
        /// </summary>
        public static string PorPagar {
            get {
                return ResourceManager.GetString("PorPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precios de Producto.
        /// </summary>
        public static string PrecioProducto {
            get {
                return ResourceManager.GetString("PrecioProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregunta Frecuentes.
        /// </summary>
        public static string Pregunta {
            get {
                return ResourceManager.GetString("Pregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        public static string Producto {
            get {
                return ResourceManager.GetString("Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorias Producto.
        /// </summary>
        public static string ProductoCategoria {
            get {
                return ResourceManager.GetString("ProductoCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        public static string Productos {
            get {
                return ResourceManager.GetString("Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promociones.
        /// </summary>
        public static string Promociones {
            get {
                return ResourceManager.GetString("Promociones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provedores.
        /// </summary>
        public static string Proveedor {
            get {
                return ResourceManager.GetString("Proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte Diario.
        /// </summary>
        public static string ReporteDiario {
            get {
                return ResourceManager.GetString("ReporteDiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte Global.
        /// </summary>
        public static string ReporteGlobal {
            get {
                return ResourceManager.GetString("ReporteGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Ventas.
        /// </summary>
        public static string ReporteMasVendidos {
            get {
                return ResourceManager.GetString("ReporteMasVendidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte Mensual.
        /// </summary>
        public static string ReporteMensual {
            get {
                return ResourceManager.GetString("ReporteMensual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponibilidad.
        /// </summary>
        public static string TipoDisponibilidad {
            get {
                return ResourceManager.GetString("TipoDisponibilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Documentos.
        /// </summary>
        public static string TipoDocumento {
            get {
                return ResourceManager.GetString("TipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Egresos.
        /// </summary>
        public static string TipoEgreso {
            get {
                return ResourceManager.GetString("TipoEgreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Movimiento en Stock.
        /// </summary>
        public static string TipoStockMovimiento {
            get {
                return ResourceManager.GetString("TipoStockMovimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicacion.
        /// </summary>
        public static string Ubicacion {
            get {
                return ResourceManager.GetString("Ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string Usuarios {
            get {
                return ResourceManager.GetString("Usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta.
        /// </summary>
        public static string Venta {
            get {
                return ResourceManager.GetString("Venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventas.
        /// </summary>
        public static string Ventas {
            get {
                return ResourceManager.GetString("Ventas", resourceCulture);
            }
        }
    }
}
