//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Libreria.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abono Asignado.
        /// </summary>
        public static string Abono {
            get {
                return ResourceManager.GetString("Abono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destino.
        /// </summary>
        public static string AccountDestination {
            get {
                return ResourceManager.GetString("AccountDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuentas.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Acumula Promociones?.
        /// </summary>
        public static string AcumulaPromos {
            get {
                return ResourceManager.GetString("AcumulaPromos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adelanto Entregado.
        /// </summary>
        public static string Adelanto {
            get {
                return ResourceManager.GetString("Adelanto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuraciones.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Estand.
        /// </summary>
        public static string AgregarEstand {
            get {
                return ResourceManager.GetString("AgregarEstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Evento.
        /// </summary>
        public static string AgregarEvento {
            get {
                return ResourceManager.GetString("AgregarEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Imagenes al a:.
        /// </summary>
        public static string AgregarImagenesTitulo {
            get {
                return ResourceManager.GetString("AgregarImagenesTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Producto.
        /// </summary>
        public static string AgregarProducto {
            get {
                return ResourceManager.GetString("AgregarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alertas.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Fantasía.
        /// </summary>
        public static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancho Mts..
        /// </summary>
        public static string Ancho {
            get {
                return ResourceManager.GetString("Ancho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        public static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abril.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atras.
        /// </summary>
        public static string Atras {
            get {
                return ResourceManager.GetString("Atras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agosto.
        /// </summary>
        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atras.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento.
        /// </summary>
        public static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobante.
        /// </summary>
        public static string BillDoc {
            get {
                return ResourceManager.GetString("BillDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador de Facturas.
        /// </summary>
        public static string BillManager {
            get {
                return ResourceManager.GetString("BillManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero.
        /// </summary>
        public static string BillNumer {
            get {
                return ResourceManager.GetString("BillNumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Comprobante.
        /// </summary>
        public static string BillType {
            get {
                return ResourceManager.GetString("BillType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string BillTypeDoc {
            get {
                return ResourceManager.GetString("BillTypeDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Factura.
        /// </summary>
        public static string BilType {
            get {
                return ResourceManager.GetString("BilType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Nacimiento.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calle.
        /// </summary>
        public static string Calle {
            get {
                return ResourceManager.GetString("Calle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar.
        /// </summary>
        public static string Cambiar {
            get {
                return ResourceManager.GetString("Cambiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de Credenciales.
        /// </summary>
        public static string CantidadCredenciales {
            get {
                return ResourceManager.GetString("CantidadCredenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad Disponible.
        /// </summary>
        public static string CantidadDisponible {
            get {
                return ResourceManager.GetString("CantidadDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado de las Cargas.
        /// </summary>
        public static string CargasStatus {
            get {
                return ResourceManager.GetString("CargasStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono asignado al Camion.
        /// </summary>
        public static string CarPhone {
            get {
                return ResourceManager.GetString("CarPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string Cerrar {
            get {
                return ResourceManager.GetString("Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destino.
        /// </summary>
        public static string ClientDestination {
            get {
                return ResourceManager.GetString("ClientDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origen.
        /// </summary>
        public static string ClientFrom {
            get {
                return ResourceManager.GetString("ClientFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de Cuentas.
        /// </summary>
        public static string ClientIndex {
            get {
                return ResourceManager.GetString("ClientIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta Destino.
        /// </summary>
        public static string Clientto {
            get {
                return ResourceManager.GetString("Clientto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo Qr.
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo de Barras.
        /// </summary>
        public static string CodigoBarras {
            get {
                return ResourceManager.GetString("CodigoBarras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo Postal.
        /// </summary>
        public static string CodigoPostal {
            get {
                return ResourceManager.GetString("CodigoPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios.
        /// </summary>
        public static string Comentaries {
            get {
                return ResourceManager.GetString("Comentaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Contraseña.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultorio.
        /// </summary>
        public static string Consultorio {
            get {
                return ResourceManager.GetString("Consultorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planilla de Contrato.
        /// </summary>
        public static string ContractTemplate {
            get {
                return ResourceManager.GetString("ContractTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactos.
        /// </summary>
        public static string Contratos {
            get {
                return ResourceManager.GetString("Contratos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario que Controlo.
        /// </summary>
        public static string ControlUser {
            get {
                return ResourceManager.GetString("ControlUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string Crear {
            get {
                return ResourceManager.GetString("Crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciales.
        /// </summary>
        public static string Credenciales {
            get {
                return ResourceManager.GetString("Credenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta.
        /// </summary>
        public static string Cuenta {
            get {
                return ResourceManager.GetString("Cuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destino.
        /// </summary>
        public static string CuentaDestino {
            get {
                return ResourceManager.GetString("CuentaDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origen.
        /// </summary>
        public static string CuentaOrigen {
            get {
                return ResourceManager.GetString("CuentaOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuit.
        /// </summary>
        public static string Cuit {
            get {
                return ResourceManager.GetString("Cuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Pedido Cumplido?.
        /// </summary>
        public static string Cumplido {
            get {
                return ResourceManager.GetString("Cumplido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Ingreso.
        /// </summary>
        public static string DateIn {
            get {
                return ResourceManager.GetString("DateIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Comprobante.
        /// </summary>
        public static string DateTicket {
            get {
                return ResourceManager.GetString("DateTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Recepcion / Envio.
        /// </summary>
        public static string DateTracking {
            get {
                return ResourceManager.GetString("DateTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diciembre.
        /// </summary>
        public static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horario de Rec. Tarde.
        /// </summary>
        public static string DeliveryAfterMoonStart {
            get {
                return ResourceManager.GetString("DeliveryAfterMoonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion de Entrega.
        /// </summary>
        public static string DeliveryDirection {
            get {
                return ResourceManager.GetString("DeliveryDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cierre.
        /// </summary>
        public static string DeliveryEnd {
            get {
                return ResourceManager.GetString("DeliveryEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horario de Rec. Mañana.
        /// </summary>
        public static string DeliveryMorningStart {
            get {
                return ResourceManager.GetString("DeliveryMorningStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derivacion.
        /// </summary>
        public static string Derivacion {
            get {
                return ResourceManager.GetString("Derivacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el numero de Derivacion.
        /// </summary>
        public static string DerivacionString {
            get {
                return ResourceManager.GetString("DerivacionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string Detalles {
            get {
                return ResourceManager.GetString("Detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diastolica.
        /// </summary>
        public static string Diastolica {
            get {
                return ResourceManager.GetString("Diastolica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta Disponible?.
        /// </summary>
        public static string Disponible {
            get {
                return ResourceManager.GetString("Disponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento de Identidad.
        /// </summary>
        public static string Documento {
            get {
                return ResourceManager.GetString("Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento de Identidad.
        /// </summary>
        public static string DocumentoIdentidad {
            get {
                return ResourceManager.GetString("DocumentoIdentidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de vencimiento poliza.
        /// </summary>
        public static string DueDatePoliza {
            get {
                return ResourceManager.GetString("DueDatePoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vencimiento de la ITV.
        /// </summary>
        public static string DueItv {
            get {
                return ResourceManager.GetString("DueItv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edad.
        /// </summary>
        public static string Edad {
            get {
                return ResourceManager.GetString("Edad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Estand.
        /// </summary>
        public static string EditarEstand {
            get {
                return ResourceManager.GetString("EditarEstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Evento.
        /// </summary>
        public static string EditarEvento {
            get {
                return ResourceManager.GetString("EditarEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Producto.
        /// </summary>
        public static string EditarProducto {
            get {
                return ResourceManager.GetString("EditarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electronico.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de Email Erroneo.
        /// </summary>
        public static string EmailFormat {
            get {
                return ResourceManager.GetString("EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entradas.
        /// </summary>
        public static string Entradas {
            get {
                return ResourceManager.GetString("Entradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entradas Generadas?.
        /// </summary>
        public static string EntradasGeneradas {
            get {
                return ResourceManager.GetString("EntradasGeneradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Nombre de Fantasía no es correcto .
        /// </summary>
        public static string ErrorAlias {
            get {
                return ResourceManager.GetString("ErrorAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Cuit debe ser Valido.
        /// </summary>
        public static string ErrorCuit {
            get {
                return ResourceManager.GetString("ErrorCuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La direccion de entrega es incorrecta .
        /// </summary>
        public static string ErrorDeliveryDirection {
            get {
                return ResourceManager.GetString("ErrorDeliveryDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Direccion no es valida.
        /// </summary>
        public static string ErrorDirection {
            get {
                return ResourceManager.GetString("ErrorDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo es requerido.
        /// </summary>
        public static string ErrorField {
            get {
                return ResourceManager.GetString("ErrorField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo requerido y el formato debe ser 00.0 sin &quot;,&quot; para separar miles.
        /// </summary>
        public static string ErrorFieldDecimal {
            get {
                return ResourceManager.GetString("ErrorFieldDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El IIBB debe ser valido.
        /// </summary>
        public static string ErrorIiBb {
            get {
                return ResourceManager.GetString("ErrorIiBb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error la longitud no cumple los requisitos.
        /// </summary>
        public static string ErrorLengthValidation {
            get {
                return ResourceManager.GetString("ErrorLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La localidad es invalida.
        /// </summary>
        public static string ErrorLocalidad {
            get {
                return ResourceManager.GetString("ErrorLocalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo de contacto es inconrrecto .
        /// </summary>
        public static string ErrorMailContact {
            get {
                return ResourceManager.GetString("ErrorMailContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad de Medida Invalida.
        /// </summary>
        public static string ErrorMeasureUnitClient {
            get {
                return ResourceManager.GetString("ErrorMeasureUnitClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Campo Nombre es Requerido.
        /// </summary>
        public static string ErrorName {
            get {
                return ResourceManager.GetString("ErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Nombre de Contacto no es Valido.
        /// </summary>
        public static string ErrorNameContact {
            get {
                return ResourceManager.GetString("ErrorNameContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Barrio es invalido.
        /// </summary>
        public static string ErrorNeighborhood {
            get {
                return ResourceManager.GetString("ErrorNeighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error las contraseñas no coinciden.
        /// </summary>
        public static string ErrorPasswordNoMatch {
            get {
                return ResourceManager.GetString("ErrorPasswordNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El telefono de Contacto.
        /// </summary>
        public static string ErrorPhoneContact {
            get {
                return ResourceManager.GetString("ErrorPhoneContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introdusca un vendedor.
        /// </summary>
        public static string ErrorSeller {
            get {
                return ResourceManager.GetString("ErrorSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Secuencia no es valida.
        /// </summary>
        public static string ErrorSequence {
            get {
                return ResourceManager.GetString("ErrorSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio invalido.
        /// </summary>
        public static string ErrorServicePrice {
            get {
                return ResourceManager.GetString("ErrorServicePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio Invalido.
        /// </summary>
        public static string ErrorServices {
            get {
                return ResourceManager.GetString("ErrorServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La condicion Iva es necesaria.
        /// </summary>
        public static string ErrorTaxCondition {
            get {
                return ResourceManager.GetString("ErrorTaxCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El horario de entrega es invalido.
        /// </summary>
        public static string ErrorTimeToDelivery {
            get {
                return ResourceManager.GetString("ErrorTimeToDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La zona no es correcta.
        /// </summary>
        public static string ErrorUbication {
            get {
                return ResourceManager.GetString("ErrorUbication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los Usuarios no son correctos.
        /// </summary>
        public static string ErrorUserReciper {
            get {
                return ResourceManager.GetString("ErrorUserReciper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Codigo postal no es valido.
        /// </summary>
        public static string ErrorZipCode {
            get {
                return ResourceManager.GetString("ErrorZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialidad Principal.
        /// </summary>
        public static string Especialidad {
            get {
                return ResourceManager.GetString("Especialidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Civil.
        /// </summary>
        public static string EstadoCivil {
            get {
                return ResourceManager.GetString("EstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estand Asignado.
        /// </summary>
        public static string Estand {
            get {
                return ResourceManager.GetString("Estand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion del Evento .
        /// </summary>
        public static string EventoDescripcion {
            get {
                return ResourceManager.GetString("EventoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es el Evento Principa?.
        /// </summary>
        public static string EventoPrincipal {
            get {
                return ResourceManager.GetString("EventoPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulo del Evento.
        /// </summary>
        public static string EventoTitulo {
            get {
                return ResourceManager.GetString("EventoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturacion.
        /// </summary>
        public static string Facturacion {
            get {
                return ResourceManager.GetString("Facturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Febrero .
        /// </summary>
        public static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Finalizacion.
        /// </summary>
        public static string FechaFin {
            get {
                return ResourceManager.GetString("FechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha y Hora.
        /// </summary>
        public static string FechaHora {
            get {
                return ResourceManager.GetString("FechaHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Incio.
        /// </summary>
        public static string FechaIncio {
            get {
                return ResourceManager.GetString("FechaIncio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Pago.
        /// </summary>
        public static string FechaPago {
            get {
                return ResourceManager.GetString("FechaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Requerido.
        /// </summary>
        public static string FieldRequiered {
            get {
                return ResourceManager.GetString("FieldRequiered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vie.
        /// </summary>
        public static string FridayShort {
            get {
                return ResourceManager.GetString("FridayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Generales.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de Cargas.
        /// </summary>
        public static string GestionCargas {
            get {
                return ResourceManager.GetString("GestionCargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion Comercial.
        /// </summary>
        public static string GestionComercial {
            get {
                return ResourceManager.GetString("GestionComercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion General.
        /// </summary>
        public static string GestionGeneral {
            get {
                return ResourceManager.GetString("GestionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de logistica.
        /// </summary>
        public static string GestionLogistica {
            get {
                return ResourceManager.GetString("GestionLogistica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grado Obtenido.
        /// </summary>
        public static string Grado {
            get {
                return ResourceManager.GetString("Grado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grado Maximo de Estudio.
        /// </summary>
        public static string GradoEstudio {
            get {
                return ResourceManager.GetString("GradoEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Sanguineo.
        /// </summary>
        public static string GrupoSanguineo {
            get {
                return ResourceManager.GetString("GrupoSanguineo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora de Fin de la Atencion.
        /// </summary>
        public static string HoraFin {
            get {
                return ResourceManager.GetString("HoraFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora de Inicio de la Atencion.
        /// </summary>
        public static string HoraInicio {
            get {
                return ResourceManager.GetString("HoraInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horario Disponible .
        /// </summary>
        public static string HorarioDisponible {
            get {
                return ResourceManager.GetString("HorarioDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secuencia Unica.
        /// </summary>
        public static string IdUnico {
            get {
                return ResourceManager.GetString("IdUnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIBB.
        /// </summary>
        public static string IiBb {
            get {
                return ResourceManager.GetString("IiBb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagenes.
        /// </summary>
        public static string Imagenes {
            get {
                return ResourceManager.GetString("Imagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importancia.
        /// </summary>
        public static string Importance {
            get {
                return ResourceManager.GetString("Importance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recepcion de Marcaderia.
        /// </summary>
        public static string Inbound {
            get {
                return ResourceManager.GetString("Inbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandeja de Entrada.
        /// </summary>
        public static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intitucion.
        /// </summary>
        public static string Institucion {
            get {
                return ResourceManager.GetString("Institucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es Instranferible?.
        /// </summary>
        public static string Instransferible {
            get {
                return ResourceManager.GetString("Instransferible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extencion interna.
        /// </summary>
        public static string Interno {
            get {
                return ResourceManager.GetString("Interno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necesita Frio.
        /// </summary>
        public static string IsCold {
            get {
                return ResourceManager.GetString("IsCold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es para todos los Usuarios?.
        /// </summary>
        public static string IsForAll {
            get {
                return ResourceManager.GetString("IsForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es Urgente?.
        /// </summary>
        public static string IsUrgent {
            get {
                return ResourceManager.GetString("IsUrgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de ITV.
        /// </summary>
        public static string Itv {
            get {
                return ResourceManager.GetString("Itv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enero.
        /// </summary>
        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julio.
        /// </summary>
        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junio.
        /// </summary>
        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilos.
        /// </summary>
        public static string Kilos {
            get {
                return ResourceManager.GetString("Kilos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximo de Kilos soportado.
        /// </summary>
        public static string KilosMaximo {
            get {
                return ResourceManager.GetString("KilosMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largo Mts.
        /// </summary>
        public static string Largo {
            get {
                return ResourceManager.GetString("Largo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite de Ingresos Diarios.
        /// </summary>
        public static string LimiteIngresos {
            get {
                return ResourceManager.GetString("LimiteIngresos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidad.
        /// </summary>
        public static string Localidad {
            get {
                return ResourceManager.GetString("Localidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Session.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo de Contacto Primario.
        /// </summary>
        public static string MailContact {
            get {
                return ResourceManager.GetString("MailContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo de Contacto Secundario.
        /// </summary>
        public static string MailContact2 {
            get {
                return ResourceManager.GetString("MailContact2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marzo.
        /// </summary>
        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayo.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad de Medidad.
        /// </summary>
        public static string MeasureUnit {
            get {
                return ResourceManager.GetString("MeasureUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad de Medida.
        /// </summary>
        public static string MeasureUnitClient {
            get {
                return ResourceManager.GetString("MeasureUnitClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miembro Desde.
        /// </summary>
        public static string MemberSince {
            get {
                return ResourceManager.GetString("MemberSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        public static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensajeria.
        /// </summary>
        public static string Messaging {
            get {
                return ResourceManager.GetString("Messaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulo.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Depende de?.
        /// </summary>
        public static string ModuloPadre {
            get {
                return ResourceManager.GetString("ModuloPadre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lun.
        /// </summary>
        public static string MondayShort {
            get {
                return ResourceManager.GetString("MondayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo de la consulta.
        /// </summary>
        public static string MotivoConsulta {
            get {
                return ResourceManager.GetString("MotivoConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Contacto Primario.
        /// </summary>
        public static string NameContact {
            get {
                return ResourceManager.GetString("NameContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Contacto Secundario.
        /// </summary>
        public static string NameContact2 {
            get {
                return ResourceManager.GetString("NameContact2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Contacto.
        /// </summary>
        public static string NameofContact {
            get {
                return ResourceManager.GetString("NameofContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre o Razon Social.
        /// </summary>
        public static string NameOrSocial {
            get {
                return ResourceManager.GetString("NameOrSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string Neighborhood {
            get {
                return ResourceManager.GetString("Neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevas Ordenes.
        /// </summary>
        public static string NewOrderIndex {
            get {
                return ResourceManager.GetString("NewOrderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombres.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Almacen.
        /// </summary>
        public static string NombreAlmacen {
            get {
                return ResourceManager.GetString("NombreAlmacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Producto.
        /// </summary>
        public static string NombreProducto {
            get {
                return ResourceManager.GetString("NombreProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaciones.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noviembre.
        /// </summary>
        public static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string Nuevo {
            get {
                return ResourceManager.GetString("Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero.
        /// </summary>
        public static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        public static string Observations {
            get {
                return ResourceManager.GetString("Observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octubre.
        /// </summary>
        public static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden de Ingreso.
        /// </summary>
        public static string Orden {
            get {
                return ResourceManager.GetString("Orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenes Completas.
        /// </summary>
        public static string OrdersIndex {
            get {
                return ResourceManager.GetString("OrdersIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origen.
        /// </summary>
        public static string Origen {
            get {
                return ResourceManager.GetString("Origen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandeja de Salida.
        /// </summary>
        public static string OutBox {
            get {
                return ResourceManager.GetString("OutBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paciente.
        /// </summary>
        public static string Paciente {
            get {
                return ResourceManager.GetString("Paciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo  Embalaje (Bultos).
        /// </summary>
        public static string PackageType {
            get {
                return ResourceManager.GetString("PackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador de Paquetes.
        /// </summary>
        public static string PackageTypeManager {
            get {
                return ResourceManager.GetString("PackageTypeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta pago?.
        /// </summary>
        public static string Pagado {
            get {
                return ResourceManager.GetString("Pagado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais.
        /// </summary>
        public static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximo de Pallets soportados.
        /// </summary>
        public static string PalletMaximo {
            get {
                return ResourceManager.GetString("PalletMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de Patente.
        /// </summary>
        public static string Patente {
            get {
                return ResourceManager.GetString("Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono de Contacto Primario.
        /// </summary>
        public static string PhoneContact {
            get {
                return ResourceManager.GetString("PhoneContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono de Contacto Secundario.
        /// </summary>
        public static string PhoneContact2 {
            get {
                return ResourceManager.GetString("PhoneContact2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono de Urgencia.
        /// </summary>
        public static string PhoneUrgenci {
            get {
                return ResourceManager.GetString("PhoneUrgenci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de Poliza.
        /// </summary>
        public static string Poliza {
            get {
                return ResourceManager.GetString("Poliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posicion.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio de Provedor.
        /// </summary>
        public static string PrecioProveedor {
            get {
                return ResourceManager.GetString("PrecioProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregunta.
        /// </summary>
        public static string Pregunta {
            get {
                return ResourceManager.GetString("Pregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precios.
        /// </summary>
        public static string Prices {
            get {
                return ResourceManager.GetString("Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Es producto principal?.
        /// </summary>
        public static string Principal {
            get {
                return ResourceManager.GetString("Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es el metodo de contacto principal?.
        /// </summary>
        public static string PrincipalContacto {
            get {
                return ResourceManager.GetString("PrincipalContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es tu especialidad Principal?.
        /// </summary>
        public static string PrincipalEspecialidad {
            get {
                return ResourceManager.GetString("PrincipalEspecialidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion Producto.
        /// </summary>
        public static string ProductoDescripcion {
            get {
                return ResourceManager.GetString("ProductoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto de Referencia.
        /// </summary>
        public static string ProductoPedido {
            get {
                return ResourceManager.GetString("ProductoPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Producto.
        /// </summary>
        public static string ProductoTitulo {
            get {
                return ResourceManager.GetString("ProductoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil de Usuario.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programacion.
        /// </summary>
        public static string Programacion {
            get {
                return ResourceManager.GetString("Programacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedores.
        /// </summary>
        public static string Providers {
            get {
                return ResourceManager.GetString("Providers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recepcion de Mercaderia.
        /// </summary>
        public static string RecepcionMercaderia {
            get {
                return ResourceManager.GetString("RecepcionMercaderia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibos.
        /// </summary>
        public static string Recibos {
            get {
                return ResourceManager.GetString("Recibos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordar.
        /// </summary>
        public static string Recordar {
            get {
                return ResourceManager.GetString("Recordar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Red Social.
        /// </summary>
        public static string RedSocial {
            get {
                return ResourceManager.GetString("RedSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de Referencia.
        /// </summary>
        public static string Referencia {
            get {
                return ResourceManager.GetString("Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo o Nombre del producto en referecia.
        /// </summary>
        public static string ReferenciaPedido {
            get {
                return ResourceManager.GetString("ReferenciaPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordar.
        /// </summary>
        public static string Remenber {
            get {
                return ResourceManager.GetString("Remenber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportes.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuestas.
        /// </summary>
        public static string Respuesta {
            get {
                return ResourceManager.GetString("Respuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen de Carrera.
        /// </summary>
        public static string Resumen {
            get {
                return ResourceManager.GetString("Resumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sab.
        /// </summary>
        public static string SaturdayShort {
            get {
                return ResourceManager.GetString("SaturdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguro.
        /// </summary>
        public static string Seguro {
            get {
                return ResourceManager.GetString("Seguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        public static string Selecionar {
            get {
                return ResourceManager.GetString("Selecionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendedor.
        /// </summary>
        public static string Seller {
            get {
                return ResourceManager.GetString("Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Senada.
        /// </summary>
        public static string Senada {
            get {
                return ResourceManager.GetString("Senada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Senasa.
        /// </summary>
        public static string Senasa {
            get {
                return ResourceManager.GetString("Senasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar Carga.
        /// </summary>
        public static string SendShip {
            get {
                return ResourceManager.GetString("SendShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Septiembre.
        /// </summary>
        public static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secuencia.
        /// </summary>
        public static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio por el total de servicios.
        /// </summary>
        public static string ServicePrice {
            get {
                return ResourceManager.GetString("ServicePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios.
        /// </summary>
        public static string Servicios {
            get {
                return ResourceManager.GetString("Servicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string Sexo {
            get {
                return ResourceManager.GetString("Sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envio de Cargas.
        /// </summary>
        public static string Shipment {
            get {
                return ResourceManager.GetString("Shipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recepcion / Evnvio de Carga.
        /// </summary>
        public static string ShipmentTrack {
            get {
                return ResourceManager.GetString("ShipmentTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Session.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistolica.
        /// </summary>
        public static string Sistolica {
            get {
                return ResourceManager.GetString("Sistolica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subir y Pre-Visualizar Imagen.
        /// </summary>
        public static string SubirVer {
            get {
                return ResourceManager.GetString("SubirVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asunto.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de session exitoso.
        /// </summary>
        public static string SucesfullyLogin {
            get {
                return ResourceManager.GetString("SucesfullyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro exitoso.
        /// </summary>
        public static string SucesfullyRegister {
            get {
                return ResourceManager.GetString("SucesfullyRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dom.
        /// </summary>
        public static string SundatShort {
            get {
                return ResourceManager.GetString("SundatShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condicion Impuestos.
        /// </summary>
        public static string TaxCondition {
            get {
                return ResourceManager.GetString("TaxCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condicion IVA.
        /// </summary>
        public static string TaxConditionLabel {
            get {
                return ResourceManager.GetString("TaxConditionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono Alternativo.
        /// </summary>
        public static string TelefonoAlternativo {
            get {
                return ResourceManager.GetString("TelefonoAlternativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatura.
        /// </summary>
        public static string Temperatura {
            get {
                return ResourceManager.GetString("Temperatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jue.
        /// </summary>
        public static string ThursdayShort {
            get {
                return ResourceManager.GetString("ThursdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horario de Recepción.
        /// </summary>
        public static string TimeToDelivery {
            get {
                return ResourceManager.GetString("TimeToDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipoAbono.
        /// </summary>
        public static string TipoAbono {
            get {
                return ResourceManager.GetString("TipoAbono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Contacto.
        /// </summary>
        public static string TipoContacto {
            get {
                return ResourceManager.GetString("TipoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Credencial.
        /// </summary>
        public static string TipoCredencial {
            get {
                return ResourceManager.GetString("TipoCredencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Documento.
        /// </summary>
        public static string TipoDocumento {
            get {
                return ResourceManager.GetString("TipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Especialidad.
        /// </summary>
        public static string TipoEspecialidad {
            get {
                return ResourceManager.GetString("TipoEspecialidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulo(Dr. Dra. ..).
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilos Totales.
        /// </summary>
        public static string TotalKilos {
            get {
                return ResourceManager.GetString("TotalKilos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de Bultos.
        /// </summary>
        public static string TotalPAckages {
            get {
                return ResourceManager.GetString("TotalPAckages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        public static string TuesdayShort {
            get {
                return ResourceManager.GetString("TuesdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicacion .
        /// </summary>
        public static string Ubicacion {
            get {
                return ResourceManager.GetString("Ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        public static string Ubication {
            get {
                return ResourceManager.GetString("Ubication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona de Partida.
        /// </summary>
        public static string UbicationFrom {
            get {
                return ResourceManager.GetString("UbicationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pertenece a:.
        /// </summary>
        public static string UbicationParent {
            get {
                return ResourceManager.GetString("UbicationParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona de Destino.
        /// </summary>
        public static string UbicationTo {
            get {
                return ResourceManager.GetString("UbicationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fue Usada?.
        /// </summary>
        public static string Usada {
            get {
                return ResourceManager.GetString("Usada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios Destinatarios.
        /// </summary>
        public static string UserDestination {
            get {
                return ResourceManager.GetString("UserDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Usuario.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administracion de Usuarios.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios Registrados.
        /// </summary>
        public static string UsersIndex {
            get {
                return ResourceManager.GetString("UsersIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles de Usuario.
        /// </summary>
        public static string UsersRoles {
            get {
                return ResourceManager.GetString("UsersRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximo Uso Fisico.
        /// </summary>
        public static string UsoFisico {
            get {
                return ResourceManager.GetString("UsoFisico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminiastrador Inicial.
        /// </summary>
        public static string UsuarioAdministrador {
            get {
                return ResourceManager.GetString("UsuarioAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario que realizo el pedido.
        /// </summary>
        public static string UsuarioPedido {
            get {
                return ResourceManager.GetString("UsuarioPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio de la Consulta Regular.
        /// </summary>
        public static string ValorConsulta {
            get {
                return ResourceManager.GetString("ValorConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio de la Consulta Urgente.
        /// </summary>
        public static string ValorUrgencia {
            get {
                return ResourceManager.GetString("ValorUrgencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta De Abono.
        /// </summary>
        public static string VentaAbono {
            get {
                return ResourceManager.GetString("VentaAbono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viigencia Desde.
        /// </summary>
        public static string VigenciaDesde {
            get {
                return ResourceManager.GetString("VigenciaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigencia Hasta.
        /// </summary>
        public static string VigenciaHasta {
            get {
                return ResourceManager.GetString("VigenciaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Vivo?.
        /// </summary>
        public static string Vivo {
            get {
                return ResourceManager.GetString("Vivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mie.
        /// </summary>
        public static string WednesdayShort {
            get {
                return ResourceManager.GetString("WednesdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo Postal.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
