//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Libreria.Resource.ValidationErrorMessages", typeof(ValidationErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Ancho es Requerido.
        /// </summary>
        public static string Ancho {
            get {
                return ResourceManager.GetString("Ancho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe selecionar un Artista.
        /// </summary>
        public static string Artista {
            get {
                return ResourceManager.GetString("Artista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Cantidad es Requerida y debe ser mayor a 0.
        /// </summary>
        public static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Candidad Disponible es requerida y debe ser mayor a 0.
        /// </summary>
        public static string CantidadDisponible {
            get {
                return ResourceManager.GetString("CantidadDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Seleccionar una Categoria.
        /// </summary>
        public static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Descripcion es Requerida.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Seleccionar Un Escenario.
        /// </summary>
        public static string Escenario {
            get {
                return ResourceManager.GetString("Escenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Seleccionar un estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Selecionar al menos 1 Etiqueta.
        /// </summary>
        public static string Etiquetas {
            get {
                return ResourceManager.GetString("Etiquetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Fecha Fin es Requerida.
        /// </summary>
        public static string FechaFin {
            get {
                return ResourceManager.GetString("FechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha y hora es necesaria.
        /// </summary>
        public static string FechaHora {
            get {
                return ResourceManager.GetString("FechaHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Fecha de Incio es Requerida.
        /// </summary>
        public static string FechaInicio {
            get {
                return ResourceManager.GetString("FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe selecionar una Imagen.
        /// </summary>
        public static string Imagen {
            get {
                return ResourceManager.GetString("Imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Largo es Necesario.
        /// </summary>
        public static string Largo {
            get {
                return ResourceManager.GetString("Largo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Valor debe ser mayor a 0.
        /// </summary>
        public static string NoCero {
            get {
                return ResourceManager.GetString("NoCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Campo Nombre es Requerido.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Numero de Credenciales es necesario.
        /// </summary>
        public static string NumeroCredenciales {
            get {
                return ResourceManager.GetString("NumeroCredenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las observaciones son requeridas.
        /// </summary>
        public static string Observaciones {
            get {
                return ResourceManager.GetString("Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Orden es requerido y debe ser mayor a 0.
        /// </summary>
        public static string Orden {
            get {
                return ResourceManager.GetString("Orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Precio es requerido.
        /// </summary>
        public static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Titulo es Requerido.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Vigencia desde es requeridad.
        /// </summary>
        public static string VigenciaDesde {
            get {
                return ResourceManager.GetString("VigenciaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Vigencia hasta es requerida.
        /// </summary>
        public static string VigenciaHasta {
            get {
                return ResourceManager.GetString("VigenciaHasta", resourceCulture);
            }
        }
    }
}
