//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewModelsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewModelsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Libreria.Resource.ViewModelsResources", typeof(ViewModelsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de Cuotas.
        /// </summary>
        public static string CantidadCuotas {
            get {
                return ResourceManager.GetString("CantidadCuotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo de Barras.
        /// </summary>
        public static string CodigoBarras {
            get {
                return ResourceManager.GetString("CodigoBarras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad Bancaria.
        /// </summary>
        public static string Entidad {
            get {
                return ResourceManager.GetString("Entidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interes de Recargo.
        /// </summary>
        public static string Interes {
            get {
                return ResourceManager.GetString("Interes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda.
        /// </summary>
        public static string Moneda {
            get {
                return ResourceManager.GetString("Moneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de Cuenta.
        /// </summary>
        public static string NumeroCuenta {
            get {
                return ResourceManager.GetString("NumeroCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es Precio Actual?.
        /// </summary>
        public static string PrecioActual {
            get {
                return ResourceManager.GetString("PrecioActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio de Proveedor.
        /// </summary>
        public static string PrecioProveedor {
            get {
                return ResourceManager.GetString("PrecioProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio a la Venta.
        /// </summary>
        public static string PrecioVenta {
            get {
                return ResourceManager.GetString("PrecioVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor.
        /// </summary>
        public static string Proveedor {
            get {
                return ResourceManager.GetString("Proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redito.
        /// </summary>
        public static string Redito {
            get {
                return ResourceManager.GetString("Redito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simbolo.
        /// </summary>
        public static string Simbolo {
            get {
                return ResourceManager.GetString("Simbolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Cambio.
        /// </summary>
        public static string TipoCambio {
            get {
                return ResourceManager.GetString("TipoCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulo Producto.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pertenece A?.
        /// </summary>
        public static string Ubicacion {
            get {
                return ResourceManager.GetString("Ubicacion", resourceCulture);
            }
        }
    }
}
